baseURL: https://danipolani.github.io/
defaultContentLanguage: ru
title: 'Dani Polani'
pagination:
  pagerSize: 8

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true


markup:
  goldmark:
    renderer:
      hardWraps: true

languages:
  ru:
    languageName: ":ru:"
    languageAltTitle: Русский
    weight: 1
    title: 'Дани Полани'
    taxonomies:
      category: categories
      tag: tags
      series: series
    params:
      authorTagline: "Некрупное и довольно доброе животное"

  en:
    languageName: ":uk:"
    languageAltTitle: English
    weight: 2
    title: Dani Polani
    params:
      authorTagline: "Rather smol and kinda friendly animal"

params:
  description: "Dani Polani - Worldbuilding and stuff"
  authorImage: "author.jpg"
  mainSections:
    - books
    - poems
    - blog
    - projects
    - worldbuilding
  google_analytics_id: "G-7542L7M944"
  showAuthorOnHomepage: false
  showAuthorOnPosts: false
  showIntroContentOnHomepage: true
