# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

# theme = "blowfish"
# baseURL = "https://your_domain.com/"
defaultContentLanguage = "ru"

enableRobotsTXT = true
paginate = 8
summaryLength = 30

buildDrafts = false
buildFuture = false

googleAnalytics = "G-7542L7M944"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
