languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 2
rtl = false

title = "Dani Poloni"
# logo = "img/logo.png"
description = "Books, worldbuilding and stuff"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Dani Poloni"
  image = "img/l23.png"
  headline = "Books, worldbuilding and stuff"
  bio = "Rather smol and kinda friendly animal"
  links = [
    { twitter = "https://twitter.com/danipolony" },
    { mastodon = "https://mastodon.ml/@danipoloni" },
    { github = "https://github.com/danipoloni" },
  ]