languageCode = "ru"
languageName = "Русский"
displayName = "RU"
isoCode = "ru"
weight = 1
rtl = false

title = "Дани Полани"
# logo = "img/logo.png"
description = "Книжки, ворлдбилдинг и всякое"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Дани Полани"
  image = "img/l23.png"
  headline = "Книжки, ворлдбилдинг и всякое"
  bio = "Некрупное и довольно доброе животное"
  links = [
    { telegram = "https://t.me/dani_tales" },
    { twitter = "https://twitter.com/danipolani" },
    { mastodon = "https://mastodon.social/@DaniPolani" },
    { github = "https://github.com/danipolani" },
  ]