languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 2
rtl = false

title = "Dani Polani"
# logo = "img/logo.png"
description = "Books, worldbuilding and stuff"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Dani Polani"
  image = "img/l23.png"
  headline = "Books, worldbuilding and stuff"
  bio = "Rather smol and kinda friendly animal"
  links = [
    { telegram = "https://t.me/dani_tales" },
    { twitter = "https://twitter.com/danipolani" },
    { mastodon = "https://mastodon.social/@DaniPolani" },
    { github = "https://github.com/danipolani" },
  ]