languageCode = "ru"
languageName = "Русский"
displayName = "RU"
isoCode = "ru"
weight = 1
rtl = false

title = "Дани Полони"
# logo = "img/logo.png"
description = "Книжки, ворлдбилдинг и всякое"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Дани Полони"
  image = "img/l23.png"
  headline = "Книжки, ворлдбилдинг и всякое"
  bio = "Некрупное и довольно доброе животное"
  links = [
    { twitter = "https://twitter.com/danipolony" },
    { mastodon = "https://mastodon.ml/@danipoloni" },
    { github = "https://github.com/danipoloni" },
  ]
