# Параметры темы hugo-winston-theme
# https://github.com/zerostaticthemes/hugo-winston-theme

twitter_handle = ""
showAuthorOnHomepage = true
showAuthorOnPosts = true
showIntroContentOnHomepage = true
showPostsOnHomepage = false
usePaginationOnHomepage = false
limitPostsOnHomepage = 8
sortPostsByDateOldestFirst = false
addDot = true
addFrame = true
highlightColor = '#7b16ff'
baseColor = "#ffffff"
baseOffsetColor = "#eaeaea"
headingColor = "#1c1b1d"
textColor = "#4e5157"
dotColor = "#7b16ff"
enableGoogleFonts = true
googleFontsUrl = "https://fonts.googleapis.com/css2?family=Wix+Madefor+Text:wght@400;500;600;700&display=swap"
fontFamilyHeading = "'Wix Madefor Text', sans-serif"
fontFamilyParagraph = "'Wix Madefor Text', sans-serif"
fontFamilyMonospace = "monospace"
